contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f441a025-b6ad-47a0-86e0-51e5c256772c
inputs:
- description: ""
  key: incident_id
  playbookInputQuery: null
  required: false
  value: {}
name: Demo - Complete Manual task
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c9acd17-5f97-40e4-8ba9-6461da09499a
      iscommand: false
      name: ""
      version: -1
    taskid: 0c9acd17-5f97-40e4-8ba9-6461da09499a
    timertriggers: []
    type: start
version: -1
