contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 1a6d72a7-4359-4321-8b67-88faa21125df
inputs: []
name: Test - data collection
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: a0752a3d-9e58-4594-8197-785ae8b21386
      iscommand: false
      name: ""
      version: -1
    taskid: a0752a3d-9e58-4594-8197-785ae8b21386
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 960,
          "y": -110
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Analyst Inputs
        options: []
        optionsarg:
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: ""
      title: Test Survey
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: Administrator
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1ea140c1-eac5-419e-8b4e-f68738f9cae6
      iscommand: false
      name: Untitled Task
      type: collection
      version: -1
    taskid: 1ea140c1-eac5-419e-8b4e-f68738f9cae6
    timertriggers: []
    type: collection
    view: |-
      {
        "position": {
          "x": 450,
          "y": 130
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      Analyst Input:
      - "4"
      LLM:
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 674f7d67-1ea0-4bc8-8ba9-bde1cbea730d
      iscommand: false
      name: 'Manual task '
      type: condition
      version: -1
    taskid: 674f7d67-1ea0-4bc8-8ba9-bde1cbea730d
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 370
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f93d101d-53c8-4999-846c-e29ce4ac8666
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: f93d101d-53c8-4999-846c-e29ce4ac8666
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 170,
          "y": 580
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 4b15cc50-6bb8-4b42-8dcb-191a466c7b44
      iscommand: false
      name: Untitled Task
      type: regular
      version: -1
    taskid: 4b15cc50-6bb8-4b42-8dcb-191a466c7b44
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 580
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8d9f28f1-ae78-46a0-89fd-7298eeb34734
      iscommand: false
      name: Send Email
      type: regular
      version: -1
    taskid: 8d9f28f1-ae78-46a0-89fd-7298eeb34734
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 960,
          "y": 50
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fea407d9-608a-4ca0-82ab-5789b147d87d
      iscommand: false
      name: wait for 3 mins
      tags:
      - taskcomplete
      type: regular
      version: -1
    taskid: fea407d9-608a-4ca0-82ab-5789b147d87d
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 960,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 785,
        "width": 1170,
        "x": 170,
        "y": -110
      }
    }
  }
