contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7f9ea5fe-77ab-47e5-8cdd-e9ab4d61f796
inputs: []
name: Demo - DataCollectionTaskWithLink
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "8"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d843fd70-6423-4eae-837c-5d84ed31d666
      iscommand: false
      name: ""
      version: -1
    taskid: d843fd70-6423-4eae-837c-5d84ed31d666
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 65
        }
      }
  "1":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Did you login from your assigned asset?
        options: []
        optionsarg:
        - {}
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      - defaultrows: []
        fieldassociated: attachment
        gridcolumns: []
        id: "1"
        label: ""
        labelarg:
          simple: Provide an evidence for that attempt
        options: []
        optionsarg: []
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: attachments
      sender: Your SOC team
      title: Unauthorized login
      totalanswers: 0
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods: []
      subject: null
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to: null
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    sla:
      days: 0
      hours: 0
      minutes: 0
      weeks: 0
    task:
      brand: ""
      id: 6f537152-ac72-497f-8d97-cff0e2d3562e
      iscommand: false
      name: Datacollectiontaskonly
      tags:
      - userreply
      type: collection
      version: -1
    taskid: 6f537152-ac72-497f-8d97-cff0e2d3562e
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: collection
    view: |-
      {
        "position": {
          "x": -385,
          "y": 205
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "2"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds
      id: 8d302c8a-fd9b-4235-8898-2b140e55e7b2
      iscommand: false
      name: Sleep
      script: Sleep
      type: regular
      version: -1
    taskid: 8d302c8a-fd9b-4235-8898-2b140e55e7b2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1200,
          "y": 300
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      bodyType:
        simple: HTML
      htmlBody:
        simple: |-
          <html>
          <body>

          <p><strong>Dear Suresh,</strong></p>
          <p>We have detected an unauthorized login attempt to your account on 2024-05-24 23:30 IST. Our security systems flagged this attempt due to unusual activity.</p>

          <p><strong>Details:</strong></p>
          <ul>
          <li>IP Address: 1.2.3.4</li>
          <li>Location: India</li>
          <li>Time: 23:30 IST</li>
          </ul>
          <p>
          Please verify if this was you. If not, we strongly recommend that you fill the form withr equired details and submit</p>
          ${Unauthorized login.Links.0.link}
          <p>If you need any assistance, please contact our support team at SOC@bac.com/+40-98345679.</p>
          <p>
          <p>T/hank you for your prompt attention to this matter.</p>
          <p>Regards,<br>Dbot</p>
          </body>
          </html>
      subject:
        simple: ${incident.id} -  Unauthorized Login Attempt Detected
      to:
        simple: sua@paloaltonetworks.com
    separatecontext: false
    skipunavailable: false
    task:
      brand: Gmail Single User
      description: Sends an email using Gmail.
      id: b1fbbac0-260e-496c-8475-85204bde48f4
      iscommand: true
      name: Sendmail
      script: Gmail Single User|||send-mail
      type: regular
      version: -1
    taskid: b1fbbac0-260e-496c-8475-85204bde48f4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1200,
          "y": 480
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              simple: Unauthorized login.Answers.0
          operator: isEqualString
          right:
            value:
              simple: "Yes"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 94ef00a8-b7f0-4a0b-8a57-f93988fc8faa
      iscommand: false
      name: Check user response
      type: condition
      version: -1
    taskid: 94ef00a8-b7f0-4a0b-8a57-f93988fc8faa
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 375
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f8aff023-dc21-4992-858b-c3104c9429c4
      iscommand: false
      name: Done
      type: regular
      version: -1
    taskid: f8aff023-dc21-4992-858b-c3104c9429c4
    timertriggers:
    - action: stop
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 925
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1eec35b9-c442-4da3-8cf6-9a88ee313688
      iscommand: false
      name: Incident response
      type: regular
      version: -1
    taskid: 1eec35b9-c442-4da3-8cf6-9a88ee313688
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 925
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7db033e3-9280-45f9-868e-2ba27bbde8a5
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 7db033e3-9280-45f9-868e-2ba27bbde8a5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1100
        }
      }
  "8":
    continueonerrortype: ""
    form:
      description: ""
      expired: false
      questions:
      - defaultrows: []
        fieldassociated: ""
        gridcolumns: []
        id: "0"
        label: ""
        labelarg:
          simple: Did you login from your assigned asset?
        options: []
        optionsarg:
        - {}
        - simple: "Yes"
        - simple: "No"
        placeholder: ""
        readonly: false
        required: false
        tooltip: ""
        type: singleSelect
      sender: Your SOC team
      title: Unauthorized login
      totalanswers: 0
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    message:
      bcc: null
      body: null
      cc: null
      format: ""
      methods:
      - email
      subject:
        simple: Test Email
      timings:
        completeafterreplies: 1
        completeaftersla: false
        completeafterv2: true
        retriescount: 2
        retriesinterval: 360
      to:
        simple: sua@paloaltonetworks.com
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    sla:
      days: 0
      hours: 0
      minutes: 0
      weeks: 0
    task:
      brand: ""
      id: c939e9cb-4c6a-4d17-8d41-9d30c2295a48
      iscommand: false
      name: Datacollectiontaskonly
      tags:
      - userreply
      type: collection
      version: -1
    taskid: c939e9cb-4c6a-4d17-8d41-9d30c2295a48
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: collection
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "9":
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 33f8446e-e940-4229-8d28-aee1b2250dc8
      iscommand: false
      name: GenericPolling
      playbookId: GenericPolling
      type: playbook
      version: -1
    taskid: 33f8446e-e940-4229-8d28-aee1b2250dc8
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 50
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 37922291-840b-4413-8c84-52a6e3882369
      iscommand: false
      name: wait for 30 mins
      tags:
      - completedemosla
      type: regular
      version: -1
    taskid: 37922291-840b-4413-8c84-52a6e3882369
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: regular
    view: |-
      {
        "position": {
          "x": 1555,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1115,
        "width": 2320,
        "x": -385,
        "y": 50
      }
    }
  }
