contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: Shift Management Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 510de779-4b48-40cf-89fa-a4c86dae4564
inputs: []
name: Shift Management
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 73d7df24-bbfb-4dc9-8188-e547ae8ffe00
      iscommand: false
      name: ""
      version: -1
    taskid: 73d7df24-bbfb-4dc9-8188-e547ae8ffe00
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": -110
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      entryID:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script will parse a CSV file and place the unique IPs, Domains
        and Hashes into the context.
      id: 9ea60da4-b6fa-42b7-8fa2-039a5f625c28
      iscommand: false
      name: Parse the shift roaster file
      script: ParseCSV
      type: regular
      version: -1
    taskid: 9ea60da4-b6fa-42b7-8fa2-039a5f625c28
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 190
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      CSVData:
        complex:
          accessor: ParsedCSV
          root: ParseCSV
          transformers:
          - args:
              from:
                value:
                  simple: "2"
              to: {}
            operator: slice
      Listname:
        simple: ShiftRoaster
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This Scripts reads the roster from Context Key ParseCSV and updates
        the list which is provided for output. Before you run this script ensure you
        run ParseCSV automation to read the uploaded CSV file
      id: 3df704b5-e652-46a3-8da4-48aee9235f7b
      iscommand: false
      name: 'Update the shift roaster details in list '
      script: d6b8de52-a100-42a3-8f19-fc7aee5b1833
      type: regular
      version: -1
    taskid: 3df704b5-e652-46a3-8da4-48aee9235f7b
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 355
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    scriptarguments:
      roles:
        simple: Analyst
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.get.users
      id: b713c4e3-59b9-45dc-8b3c-8dfc97d13228
      iscommand: true
      name: 'getUsers list '
      script: Builtin|||getUsers
      type: regular
      version: -1
    taskid: b713c4e3-59b9-45dc-8b3c-8dfc97d13228
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 25
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      date:
        simple: ${date}
      user:
        simple: ${DemistoUsers.username}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 19cfc17f-fce9-48c7-8a35-543029ce3fc6
      iscommand: false
      name: Shift Management - Update Employee Shift
      playbookId: ca701905-a39e-45ba-82e8-eb6440969ca0
      type: playbook
      version: -1
    taskid: 19cfc17f-fce9-48c7-8a35-543029ce3fc6
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 50,
          "y": 900
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Retrieves the current date and time.
      id: 0eb88280-b2b2-48f2-8873-8569edc3ef8c
      iscommand: false
      name: Get Time
      script: GetTime
      type: regular
      version: -1
    taskid: 0eb88280-b2b2-48f2-8873-8569edc3ef8c
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 530
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: date
      value:
        complex:
          root: TimeNowUnix
          transformers:
          - args:
              format:
                value:
                  simple: 02-Jan
            operator: toString
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 3b3c73c6-dc30-402d-8394-f11aaf6e2b89
      iscommand: false
      name: Set Date format
      script: Set
      type: regular
      version: -1
    taskid: 3b3c73c6-dc30-402d-8394-f11aaf6e2b89
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 700
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1105,
        "width": 380,
        "x": 50,
        "y": -110
      }
    }
  }
