contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: be764b58-4b3b-4204-8019-00df96ada2a7
inputs: []
name: TestOzan44
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: d2ec9f8f-76c7-48bb-8b01-c9ce74418305
      iscommand: false
      name: ""
      version: -1
    taskid: d2ec9f8f-76c7-48bb-8b01-c9ce74418305
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 5336eac0-73d3-4b16-8670-ca95096cd6cc
      iscommand: false
      name: TestOzan45
      script: bc322780-3c21-4037-8a1a-7f8d6c3d77e8
      tags:
      - Test44Tag
      type: regular
      version: -1
    taskid: 5336eac0-73d3-4b16-8670-ca95096cd6cc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 240
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 285,
        "width": 390,
        "x": 450,
        "y": 50
      }
    }
  }
