contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f7cd184d-0896-4b4d-869d-9c1576512979
inputs:
- description: ""
  key: InstanceName
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: F5_Instance_Names
      root: lists
      transformers:
      - args:
          delimiter:
            value:
              simple: ','
        operator: split
name: SampleBCAPlaybook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 48c200c8-cb46-4bea-88ea-bd128f232be0
      iscommand: false
      name: ""
      version: -1
    taskid: 48c200c8-cb46-4bea-88ea-bd128f232be0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
