contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 7938a406-da30-4828-8e55-d766cececc26
inputs:
- description: ""
  key: pageno
  playbookInputQuery: null
  required: false
  value:
    simple: ${iterator}
name: Report Download - Incident Search
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0f1d8677-2995-4652-86ee-cee6b698e6c2
      iscommand: false
      name: ""
      version: -1
    taskid: 0f1d8677-2995-4652-86ee-cee6b698e6c2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      key:
        simple: Iterator
      value:
        complex:
          root: ${iterator}
          transformers:
          - args:
              by:
                value:
                  simple: "1"
            operator: subtraction
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Set a value in context under the key you entered.
      id: 25ccd930-3846-49d4-8bdd-470317d6e46e
      iscommand: false
      name: Set Page no
      script: Set
      type: regular
      version: -1
    taskid: 25ccd930-3846-49d4-8bdd-470317d6e46e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 250
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 295,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
