contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f7cd184d-0896-4b4d-869d-9c1576512979
inputs:
- description: ""
  key: InstanceName
  playbookInputQuery: null
  required: false
  value:
    complex:
      accessor: F5_Instance_Names
      root: lists
      transformers:
      - args:
          delimiter:
            value:
              simple: ','
        operator: split
name: SampleBCAPlaybookSubplaybook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 48c200c8-cb46-4bea-88ea-bd128f232be0
      iscommand: false
      name: ""
      version: -1
    taskid: 48c200c8-cb46-4bea-88ea-bd128f232be0
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f1d2ce15-9989-4fb1-85f0-3e06a5e5dd85
      iscommand: false
      name: get token
      type: regular
      version: -1
    taskid: f1d2ce15-9989-4fb1-85f0-3e06a5e5dd85
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c5ed7f92-63e2-45a6-86e5-352cf7588df2
      iscommand: false
      name: get Data
      type: regular
      version: -1
    taskid: c5ed7f92-63e2-45a6-86e5-352cf7588df2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 440
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 30ca7c2c-8566-4cb0-8ff8-382f0a4f4111
      iscommand: false
      name: Insert Data
      type: regular
      version: -1
    taskid: 30ca7c2c-8566-4cb0-8ff8-382f0a4f4111
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 440,
          "y": 630
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      all:
        simple: "yes"
      keysToKeep:
        simple: incident
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Delete field from context.\n\nThis automation runs using the default
        Limited User role, unless you explicitly change the permissions.\nFor more
        information, see the section about permissions here:\n- For Cortex XSOAR 6
        see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/6.x/Cortex-XSOAR-Playbook-Design-Guide/Automations
        \n- For Cortex XSOAR 8 Cloud see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8/Cortex-XSOAR-Cloud-Documentation/Create-a-script\n-
        For Cortex XSOAR 8.7 On-prem see https://docs-cortex.paloaltonetworks.com/r/Cortex-XSOAR/8.7/Cortex-XSOAR-On-prem-Documentation/Create-a-script"
      id: d66e50cf-1ec5-4b12-805c-af192595d7e1
      iscommand: false
      name: Delete Context
      script: DeleteContext
      type: regular
      version: -1
    taskid: d66e50cf-1ec5-4b12-805c-af192595d7e1
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 430,
          "y": 840
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 885,
        "width": 400,
        "x": 430,
        "y": 50
      }
    }
  }
