contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: b6b0558c-3a60-4a25-8775-b72e832e359e
inputs: []
name: testPlaybook
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 40e686d0-701a-46f1-80c0-be961af8bb06
      iscommand: false
      name: ""
      version: -1
    taskid: 40e686d0-701a-46f1-80c0-be961af8bb06
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 908dc9bf-574a-4153-8877-78355293da2f
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: 908dc9bf-574a-4153-8877-78355293da2f
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 225,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
