contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 215d4630-14a1-439e-8c64-a6cea49dbbb0
inputs: []
name: Indicator Migration
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: eb86d4e3-b842-4512-874b-dc1a7517ad66
      iscommand: false
      name: ""
      version: -1
    taskid: eb86d4e3-b842-4512-874b-dc1a7517ad66
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      add_fields_to_context:
        simple: tags,modifiedTime,firstseenbysource,reliability,lastReputationRun,modified,sourceBrands,expiration,expirationStatus
      query:
        simple: sourceBrands:"Unit42v2 Feed" and type:IP tags:MaliciousIP
      size:
        simple: "1000"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Cortex XSOAR Indicators.

        Search for XSOAR Indicators and returns the id, indicator_type, value, and score/verdict.

        You can add additional fields from the indicators using the add_field_to_context argument.
      id: b953efa0-092f-4f7d-8128-a88f7b583095
      iscommand: false
      name: Search Indicators
      script: SearchIndicator
      type: regular
      version: -1
    taskid: b953efa0-092f-4f7d-8128-a88f7b583095
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    loop:
      exitCondition: ""
      forEach: true
      iscommand: false
      max: 100
      wait: 1
    note: false
    quietmode: 0
    scriptarguments:
      IndicatorData:
        simple: ${foundIndicators}
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 320a501d-6019-4378-887f-553307675cfc
      iscommand: false
      name: Indicator creation XSOAR8
      playbookId: 6f8dd3c4-7f2d-4ffc-856a-9ba0a7d6f8da
      type: playbook
      version: -1
    taskid: 320a501d-6019-4378-887f-553307675cfc
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
