contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 54e770b2-f478-4b46-8eb1-a06eff58876b
inputs: []
name: Ozan Test 1
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f303053f-fcba-409a-8c0f-762341cb623a
      iscommand: false
      name: ""
      version: -1
    taskid: f303053f-fcba-409a-8c0f-762341cb623a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Ozan Test 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: 8f41d7f6-bba7-4ee2-859f-3b1849d37255
      iscommand: false
      name: PrintUntitled Task
      script: Print
      type: regular
      version: -1
    taskid: 8f41d7f6-bba7-4ee2-859f-3b1849d37255
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 330
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e66f028d-4a26-4356-8869-2297b21e21e7
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: e66f028d-4a26-4356-8869-2297b21e21e7
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 440,
          "y": 540
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 555,
        "width": 400,
        "x": 440,
        "y": 50
      }
    }
  }
