contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 763c324d-10e1-46d1-8dc7-25e4d94bc3fc
inputs: []
name: Demo - Service Now Ticket3
outputs: []
sourceplaybookid: c3573998-e06b-4926-86b0-c0f3de27f997
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 7a57d1ee-4d28-4d83-8ce7-22b296071508
      iscommand: false
      name: ""
      version: -1
    taskid: 7a57d1ee-4d28-4d83-8ce7-22b296071508
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -90
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      assignment_group:
        simple: Incident Management
      caller_id:
        simple: courtney.shishido
      category:
        simple: Network
      impact:
        simple: 2 - Medium
      short_description:
        simple: Test Incident 3
      subcategory:
        simple: VPN
      urgency:
        simple: 2 - Medium
    separatecontext: false
    skipunavailable: false
    task:
      brand: ServiceNow v2
      description: Creates new ServiceNow ticket.
      id: 6d500b1a-91df-442f-83cf-f94ca1748070
      iscommand: true
      name: Create Service Now ticket
      script: ServiceNow v2|||servicenow-create-ticket
      type: regular
      version: -1
    taskid: 6d500b1a-91df-442f-83cf-f94ca1748070
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 40
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      dbotMirrorDirection:
        simple: In
      dbotMirrorId:
        simple: ${ServiceNow.Ticket.ID}
      dbotMirrorInstance:
        simple: ServiceNow v2_instance_1
      dbotMirrorTags:
        simple: comments,CommentFromServiceNow,ForServiceNow,FromServiceNow,work_notes,WorkNoteFromServiceNow
      servicenowcategory:
        simple: ${ServiceNow.Ticket.category}
      servicenowpriority:
        simple: ${ServiceNow.Ticket.Priority}
      servicenowstate:
        complex:
          accessor: State
          root: ServiceNow.Ticket
          transformers:
          - args:
              input_values:
                value:
                  simple: 1,2,3,4,5,6,7,8
              mapped_values:
                value:
                  simple: New,In Progress,On-Hold,Awaiting Caller,Awaiting Evidence,Resolved,Closed,Canceled
            operator: MapValuesTransformer
      servicenowticketnumber:
        simple: ${ServiceNow.Ticket.Number}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 25fa8d74-05fd-4b37-8940-a24ed540dc13
      iscommand: true
      name: Set Mirroring Fields
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 25fa8d74-05fd-4b37-8940-a24ed540dc13
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c82bae9-47ba-4525-8169-b4dd01995702
      iscommand: false
      name: waiting for analyst response
      tags:
      - remediate
      type: regular
      version: -1
    taskid: 9c82bae9-47ba-4525-8169-b4dd01995702
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 480
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 665,
        "width": 380,
        "x": 450,
        "y": -90
      }
    }
  }
