contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: af9b6909-cc13-4a71-8ccc-bc6ead1f5712
inputs: []
name: TestDemoPlaybook-Dev
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3b17b525-9349-4073-8dc2-1801a5757b9f
      iscommand: false
      name: ""
      version: -1
    taskid: 3b17b525-9349-4073-8dc2-1801a5757b9f
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 60
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: fa5a430b-fee1-4f25-8bb3-bc2f4fd35c18
      iscommand: false
      name: Access Investigation - Generic
      playbookId: access_investigation_-_generic
      type: playbook
      version: -1
    taskid: fa5a430b-fee1-4f25-8bb3-bc2f4fd35c18
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 240
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: true
    skipunavailable: false
    task:
      brand: ""
      id: 419761e1-09fe-461f-82f7-737bb088760d
      iscommand: false
      name: Account Enrichment - Generic v2.1
      playbookId: Account Enrichment - Generic v2.1
      type: playbook
      version: -1
    taskid: 419761e1-09fe-461f-82f7-737bb088760d
    timertriggers: []
    type: playbook
    view: |-
      {
        "position": {
          "x": 450,
          "y": 420
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 455,
        "width": 380,
        "x": 450,
        "y": 60
      }
    }
  }
