contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 230329fa-ba5c-4609-85f1-27342e713aee
inputs: []
name: Ozan Test 2
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 85edeab2-807a-4128-80ef-e230f2859493
      iscommand: false
      name: ""
      version: -1
    taskid: 85edeab2-807a-4128-80ef-e230f2859493
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Ozan 2
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: e96d10db-9ca1-4d9f-8e02-74304153371d
      iscommand: false
      name: Untitled Task
      script: Print
      type: regular
      version: -1
    taskid: e96d10db-9ca1-4d9f-8e02-74304153371d
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 210
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      execution-timeout:
        simple: "5"
      name:
        simple: Ozan Test 1
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.playbook
      id: 4a65f82b-c1cf-4cf6-8631-44ffc78c48ce
      iscommand: true
      name: setUntitled Task
      script: Builtin|||setPlaybook
      type: regular
      version: -1
    taskid: 4a65f82b-c1cf-4cf6-8631-44ffc78c48ce
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 460
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e3835a35-c2c3-4ff2-8ef3-fea8ab2df857
      iscommand: false
      name: Untitled Task
      type: title
      version: -1
    taskid: e3835a35-c2c3-4ff2-8ef3-fea8ab2df857
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 500,
          "y": 950
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      value:
        simple: Winston
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Prints text to war room (Markdown supported)
      id: d5ae2c2a-33c6-4d5a-89f4-6e8dc3600464
      iscommand: false
      name: Print
      script: Print
      type: regular
      version: -1
    taskid: d5ae2c2a-33c6-4d5a-89f4-6e8dc3600464
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 720
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 965,
        "width": 430,
        "x": 450,
        "y": 50
      }
    }
  }
