contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: f441a025-b6ad-47a0-86e0-51e5c256772c
inputs:
- description: ""
  key: incident_id
  playbookInputQuery: null
  required: false
  value: {}
name: Demo - Complete Manual task
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0c9acd17-5f97-40e4-8ba9-6461da09499a
      iscommand: false
      name: ""
      version: -1
    taskid: 0c9acd17-5f97-40e4-8ba9-6461da09499a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 460,
          "y": 30
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      id:
        simple: Splunk
      incidentId:
        simple: ${inputs.incident_id}
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.task.complete
      id: 86192abb-ca8b-4ce9-8294-5c426f71f9ed
      iscommand: true
      name: complete the manual task
      script: Builtin|||taskComplete
      type: regular
      version: -1
    taskid: 86192abb-ca8b-4ce9-8294-5c426f71f9ed
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 460,
          "y": 190
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 460,
        "y": 30
      }
    }
  }
