contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 26afc790-9251-4de4-80b0-3b93fad377c4
inputs:
- description: ""
  key: listName
  playbookInputQuery: null
  required: true
  value: {}
- description: ""
  key: value
  playbookInputQuery: null
  required: true
  value: {}
name: ICICI - Add to Reference Set
outputs: []
starttaskid: "0"
tags:
- TI
- Phishing
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 3e2c96cf-bc91-4b17-81b9-bbc984d98ade
      iscommand: false
      name: ""
      version: -1
    taskid: 3e2c96cf-bc91-4b17-81b9-bbc984d98ade
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 265,
          "y": 50
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 0
    scriptarguments:
      date_value:
        simple: "False"
      ref_name:
        simple: ${inputs.listName}
      retry-count:
        simple: "3"
      retry-interval:
        simple: "50"
      source:
        simple: XSOAR - Qradar API
      value:
        simple: ${inputs.value}
    separatecontext: false
    skipunavailable: false
    task:
      brand: QRadar_v2
      description: Add or update a value in a reference set.
      id: 3f2a669a-3818-44b6-861f-23ddd0c88616
      iscommand: true
      name: Add to reference Set Domain
      script: QRadar_v2|||qradar-create-reference-set-value
      type: regular
      version: -1
    taskid: 3f2a669a-3818-44b6-861f-23ddd0c88616
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
  "3":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: isEqualString
                    right:
                      value:
                        simple: QRadarv3_instance_1
                root: modules.name
          operator: isEqualString
          right:
            value:
              simple: QRadarv3_instance_1
      - - left:
            iscontext: true
            value:
              complex:
                accessor: state
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: isEqualString
                    right:
                      value:
                        simple: QRadarv3_instance_1
                root: modules
          operator: isEqualString
          right:
            value:
              simple: active
      label: QRadar_v3_instance_1
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: isEqualString
                    right:
                      value:
                        simple: QRadar_v2_instance_1
                root: modules.name
          operator: isEqualString
          right:
            value:
              simple: QRadar_v2_instance_1
      - - left:
            iscontext: true
            value:
              complex:
                accessor: state
                filters:
                - - left:
                      iscontext: true
                      value:
                        simple: modules.name
                    operator: isEqualString
                    right:
                      value:
                        simple: QRadar_v2_instance_1
                root: modules
          operator: isEqualString
          right:
            value:
              simple: active
      label: QRadar_v2_instance_1
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      QRadar_v2_instance_1:
      - "2"
      QRadar_v3_instance_1:
      - "7"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 40fede5b-a87c-41a0-8544-279acf8a8452
      iscommand: false
      name: Select available Integration
      type: condition
      version: -1
    taskid: 40fede5b-a87c-41a0-8544-279acf8a8452
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 265,
          "y": 195
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c496a51-0d07-47ca-8e92-c768fdcb0bd6
      iscommand: false
      name: END
      type: title
      version: -1
    taskid: 9c496a51-0d07-47ca-8e92-c768fdcb0bd6
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 265,
          "y": 545
        }
      }
  "7":
    continueonerrortype: ""
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "5"
    note: false
    quietmode: 1
    scriptarguments:
      date_value:
        simple: "False"
      ref_name:
        simple: ${inputs.listName}
      retry-count:
        simple: "5"
      retry-interval:
        simple: "30"
      source:
        simple: XSOAR - Qradar API
      value:
        simple: ${inputs.value}
    separatecontext: false
    skipunavailable: false
    task:
      brand: QRadar v3
      description: Adds or updates an element in a reference set.
      id: 8fdab8eb-ba19-4ca5-8b19-25776a2d9dfa
      iscommand: true
      name: Add to reference Set Domain
      script: QRadar v3|||qradar-reference-set-value-upsert
      type: regular
      version: -1
    taskid: 8fdab8eb-ba19-4ca5-8b19-25776a2d9dfa
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {
      "3_7_QRadar_v3_instance_1": 0.87
    },
    "paper": {
      "dimensions": {
        "height": 560,
        "width": 810,
        "x": 50,
        "y": 50
      }
    }
  }
