contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 25e9a140-8e11-498f-8245-a5940323bbd2
inputs: []
name: Demo - SLA Timer
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f3bf44b9-41e9-4709-8add-34020b5f1a0a
      iscommand: false
      name: ""
      version: -1
    taskid: f3bf44b9-41e9-4709-8add-34020b5f1a0a
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c1b49736-1045-460e-81f8-5c6135e76861
      iscommand: false
      name: Start Demo SLA Timer
      type: title
      version: -1
    taskid: c1b49736-1045-460e-81f8-5c6135e76861
    timertriggers:
    - action: start
      fieldname: demoslatimer
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 220
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 9c40b19a-1452-4fbc-879f-80711bb5eb58
      iscommand: false
      name: Complete the task once SLA/timer breaches
      tags:
      - taskcomplete
      type: regular
      version: -1
    taskid: 9c40b19a-1452-4fbc-879f-80711bb5eb58
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 475,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
