contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: Shift Management Contribution Pack
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: ca701905-a39e-45ba-82e8-eb6440969ca0
inputs:
- description: ""
  key: user
  playbookInputQuery: null
  required: false
  value: {}
- description: ""
  key: date
  playbookInputQuery: null
  required: false
  value: {}
name: Shift Management - Update Employee Shift
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 8406198c-beaa-4da8-89c4-1bea3fe3379e
      iscommand: false
      name: ""
      version: -1
    taskid: 8406198c-beaa-4da8-89c4-1bea3fe3379e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -100
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      date:
        simple: ${inputs.date}
      defaultRole:
        simple: Analyst
      employee:
        simple: ${inputs.user}
      listname:
        simple: ShiftRoaster
      roleA:
        simple: ShiftA
      roleB:
        simple: ShiftB
      roleC:
        simple: ShiftC
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: This script will read the input Employee Name and Employee Date
        , extract Employee Shift based on these 2 arguments and update the role of
        the employee
      id: 89047f97-5951-4b1f-8212-fdfebee9e877
      iscommand: false
      name: Update the Employee Shift
      script: 7444b010-42ba-426c-8dc9-ec9024e567de
      type: regular
      version: -1
    taskid: 89047f97-5951-4b1f-8212-fdfebee9e877
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 620,
          "y": 450
        }
      }
  "2":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: ShiftRoaster
                root: lists
                transformers:
                - args:
                    field:
                      iscontext: true
                      value:
                        simple: inputs.user
                  operator: getField
                - args:
                    field:
                      iscontext: true
                      value:
                        simple: inputs.date
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: "OFF"
      label: "yes"
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "1"
      "yes":
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: c8ae186c-5b01-4df3-8cd9-2c4a4b082aa9
      iscommand: false
      name: Check User is on OFF or not
      type: condition
      version: -1
    taskid: c8ae186c-5b01-4df3-8cd9-2c4a4b082aa9
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      daysoff:
        simple: "1"
      option:
        simple: add
      username:
        simple: ${inputs.user}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Adds or removes an analyst from the out-of-office list in XSOAR.
        When used with the AssignAnalystToIncidentOOO automation, prevents incidents
        from being assigned to an analyst who is out of office.
      id: fdfbf184-d8b2-4745-868a-e1e5ded41193
      iscommand: false
      name: Update OOO users List
      script: ManageOOOusers
      type: regular
      version: -1
    taskid: fdfbf184-d8b2-4745-868a-e1e5ded41193
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": -20,
          "y": 430
        }
      }
  "4":
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f90396ad-10f4-4495-8bf0-3bc6fd6f58a5
      iscommand: false
      name: End
      type: title
      version: -1
    taskid: f90396ad-10f4-4495-8bf0-3bc6fd6f58a5
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": -20,
          "y": 770
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 935,
        "width": 1020,
        "x": -20,
        "y": -100
      }
    }
  }
