contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 8082a43c-0e98-401e-8dd9-4497ebf61d91
inputs: []
name: Shift Management JOB
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 12a037eb-7a17-444d-8ed4-dd265947600b
      iscommand: false
      name: ""
      version: -1
    taskid: 12a037eb-7a17-444d-8ed4-dd265947600b
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      entryId:
        simple: ${File.EntryID}
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: The automation takes Excel file (entryID) as an input and parses
        its content to the war room and context.
      id: bd9515cb-7f70-418e-8fec-a91eff3469a8
      iscommand: false
      name: Parse Excel
      script: ParseExcel
      type: regular
      version: -1
    taskid: bd9515cb-7f70-418e-8fec-a91eff3469a8
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 210
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 255,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
