contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 30d6d1c6-1dba-4871-8e16-85bca04bf0b8
inputs:
- description: ""
  key: Data
  playbookInputQuery: null
  required: false
  value:
    simple: ${ProcessedIndicators}
- description: ""
  key: name
  playbookInputQuery: null
  required: false
  value: {}
name: ICICI Export Indicator To CSV SUB
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "9"
      - "11"
      - "12"
      - "13"
      - "15"
      - "14"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 337a7973-544d-4e47-87f9-19446ca24d37
      iscommand: false
      name: ""
      version: -1
    taskid: 337a7973-544d-4e47-87f9-19446ca24d37
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 1030,
          "y": -550
        }
      }
  "2":
    continueonerror: true
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: 'Extracted Domain List '
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: Domain
          root: inputs.Data
          transformers:
          - args:
              separator:
                value:
                  simple: |2+

            operator: join
      filename:
        simple: ${incident.id}_${inputs.name}_IOC_Report_Domain.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: 3fd4e702-25cd-48c2-804e-29af217b8cab
      iscommand: false
      name: 'Domain To CSV '
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 3fd4e702-25cd-48c2-804e-29af217b8cab
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 428d09b9-a31a-43ed-8614-cf98a3b93eb4
      iscommand: false
      name: END
      type: title
      version: -1
    taskid: 428d09b9-a31a-43ed-8614-cf98a3b93eb4
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1125,
          "y": 370
        }
      }
  "4":
    continueonerror: true
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Extracted URL List
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: URL
          root: inputs.Data
          transformers:
          - args:
              separator:
                value:
                  simple: |2+

            operator: join
      filename:
        simple: ${incident.id}_${inputs.name}_IOC_Report_URL.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: 20b75376-d7b7-42da-8d85-3843357b5db9
      iscommand: false
      name: 'URL To CSV '
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 20b75376-d7b7-42da-8d85-3843357b5db9
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 480,
          "y": 195
        }
      }
  "5":
    continueonerror: true
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Extracted Email List
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: Email
          root: inputs.Data
          transformers:
          - args:
              separator:
                value:
                  simple: |2+

            operator: join
      filename:
        simple: ${incident.id}_IOC_Report_${inputs.name}_Email.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: d3960721-ca2f-4904-817a-740069d7fccf
      iscommand: false
      name: 'EMAIL To CSV '
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: d3960721-ca2f-4904-817a-740069d7fccf
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 910,
          "y": 195
        }
      }
  "6":
    continueonerror: true
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Extracted IP List
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: IP
          root: inputs.Data
          transformers:
          - args:
              separator:
                value:
                  simple: |2+

            operator: join
      filename:
        simple: ${incident.id}_${inputs.name}_IOC_Report_IP.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: 34fad6b5-bcbb-4618-8286-e379eef1f60a
      iscommand: false
      name: 'IP To CSV '
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: 34fad6b5-bcbb-4618-8286-e379eef1f60a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1340,
          "y": 195
        }
      }
  "7":
    continueonerror: true
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: Extracted Hash List
    id: "7"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: File
          root: inputs.Data
          transformers:
          - args:
              separator:
                value:
                  simple: |2+

            operator: join
      filename:
        simple: ${incident.id}_IOC_${inputs.name}_Report_Hash.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: f28da39b-0c96-43d0-83de-056b49e3abc7
      iscommand: false
      name: 'HASH To CSV '
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: f28da39b-0c96-43d0-83de-056b49e3abc7
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 1770,
          "y": 195
        }
      }
  "8":
    continueonerror: true
    continueonerrortype: ""
    evidencedata:
      customfields: {}
      description:
        simple: 'Extracted CSV List '
    id: "8"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    scriptarguments:
      data:
        complex:
          accessor: CVE
          root: inputs.Data
          transformers:
          - args:
              separator:
                value:
                  simple: |2+

            operator: join
      filename:
        simple: ${incident.id}_${inputs.name}_IOC_Report_CVE.csv
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |
        Will create a file (using the given data input or entry ID) and upload it to current investigation war room.
      id: e27a9b41-6b24-4676-8e6f-2df4ece0b28a
      iscommand: false
      name: 'CVE To CSV '
      script: FileCreateAndUpload
      type: regular
      version: -1
    taskid: e27a9b41-6b24-4676-8e6f-2df4ece0b28a
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 2200,
          "y": 195
        }
      }
  "9":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Data
                transformers:
                - args:
                    field:
                      value:
                        simple: IP
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: NA
      label: IP Not available
    continueonerrortype: ""
    id: "9"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "6"
      IP Not available:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 487f59e6-cb2d-4e37-8304-de812db460af
      iscommand: false
      name: IF IP NA
      type: condition
      version: -1
    taskid: 487f59e6-cb2d-4e37-8304-de812db460af
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1180,
          "y": -300
        }
      }
  "10":
    continueonerrortype: ""
    id: "10"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 65dfc128-4d7a-4ea4-8b6a-c2af6ca3091b
      iscommand: false
      name: 'NA '
      type: title
      version: -1
    taskid: 65dfc128-4d7a-4ea4-8b6a-c2af6ca3091b
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 1000,
          "y": 50
        }
      }
  "11":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Data
                transformers:
                - args:
                    field:
                      value:
                        simple: Domain
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: NA
      label: Domain Not available
    continueonerrortype: ""
    id: "11"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      Domain Not available:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 1d5e680b-f8c5-482a-8b2d-e04f206b9f59
      iscommand: false
      name: IF Domain na
      type: condition
      version: -1
    taskid: 1d5e680b-f8c5-482a-8b2d-e04f206b9f59
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": -10,
          "y": -380
        }
      }
  "12":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Data
                transformers:
                - args:
                    field:
                      value:
                        simple: URL
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: NA
      label: URL Not available
    continueonerrortype: ""
    id: "12"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "4"
      URL Not available:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 57a1832b-f0ee-4245-810e-5d9820665229
      iscommand: false
      name: IF URL NA
      type: condition
      version: -1
    taskid: 57a1832b-f0ee-4245-810e-5d9820665229
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 430,
          "y": -360
        }
      }
  "13":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Data
                transformers:
                - args:
                    field:
                      value:
                        simple: File
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: NA
      label: Hash Not available
    continueonerrortype: ""
    id: "13"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "7"
      Hash Not available:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 795807ff-8e13-4235-8fa3-83c4276163de
      iscommand: false
      name: IF Hash NA
      type: condition
      version: -1
    taskid: 795807ff-8e13-4235-8fa3-83c4276163de
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1570,
          "y": -300
        }
      }
  "14":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Data
                transformers:
                - args:
                    field:
                      value:
                        simple: CVE
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: NA
      label: CVE Not available
    continueonerrortype: ""
    id: "14"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "8"
      CVE Not available:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: da8b356e-00f4-4ffc-85a8-9c45e756ee4b
      iscommand: false
      name: IF CVE NA
      type: condition
      version: -1
    taskid: da8b356e-00f4-4ffc-85a8-9c45e756ee4b
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 1960,
          "y": -300
        }
      }
  "15":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                root: inputs.Data
                transformers:
                - args:
                    field:
                      value:
                        simple: Email
                  operator: getField
          operator: isEqualString
          right:
            value:
              simple: NA
      label: Email Not available
    continueonerrortype: ""
    id: "15"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "5"
      Email Not available:
      - "10"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: f0ea8798-a9a7-4234-8653-0521ce2e92fe
      iscommand: false
      name: IF Email NA
      type: condition
      version: -1
    taskid: f0ea8798-a9a7-4234-8653-0521ce2e92fe
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 790,
          "y": -300
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 985,
        "width": 2590,
        "x": -10,
        "y": -550
      }
    }
  }
