contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e330cea0-228d-4aca-8a99-99c089337688
inputs: []
name: Demo - Indicators
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fe796328-745b-4eb5-8d88-8846ba7691e2
      iscommand: false
      name: ""
      version: -1
    taskid: fe796328-745b-4eb5-8d88-8846ba7691e2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 65,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
