contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e34441dd-18f6-47b4-8789-814a04028e8a
inputs: []
name: jobtest
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 0b0f7f5f-2ab2-4751-811d-f1a4c225328e
      iscommand: false
      name: ""
      version: -1
    taskid: 0b0f7f5f-2ab2-4751-811d-f1a4c225328e
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      seconds:
        simple: "60"
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sleep for X seconds.
      id: 23e2940d-0507-41f6-8fe1-d92c331e8594
      iscommand: false
      name: Sleep for a min
      script: Sleep
      type: regular
      version: -1
    taskid: 23e2940d-0507-41f6-8fe1-d92c331e8594
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 200
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.close.inv
      id: efd87099-27bd-42b1-855d-f5e7fa2a2ed2
      iscommand: true
      name: close investigation
      script: Builtin|||closeInvestigation
      type: regular
      version: -1
    taskid: efd87099-27bd-42b1-855d-f5e7fa2a2ed2
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": 410
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 13b0ae02-52bc-49e0-805e-b24adf848f29
      iscommand: false
      name: done
      type: title
      version: -1
    taskid: 13b0ae02-52bc-49e0-805e-b24adf848f29
    timertriggers: []
    type: title
    view: |-
      {
        "position": {
          "x": 450,
          "y": 560
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 575,
        "width": 380,
        "x": 450,
        "y": 50
      }
    }
  }
