contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: 21801d37-9d54-4e8b-8dc6-149c506ec23d
inputs: []
name: Demo Manual Playbook
outputs: []
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "3"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 379844be-1517-4667-83bb-17b3309fd54c
      iscommand: false
      name: ""
      version: -1
    taskid: 379844be-1517-4667-83bb-17b3309fd54c
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 450,
          "y": -180
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      roles:
        simple: Analyst
    separatecontext: false
    skipunavailable: false
    task:
      brand: Builtin
      description: commands.local.cmd.set.incident
      id: 613bdac9-3621-42f6-8315-407a137bb952
      iscommand: true
      name: 'Set role '
      script: Builtin|||setIncident
      type: regular
      version: -1
    taskid: 613bdac9-3621-42f6-8315-407a137bb952
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 680,
          "y": 360
        }
      }
  "3":
    continueonerrortype: ""
    id: "3"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "4"
    note: false
    quietmode: 0
    scriptarguments:
      fromdate:
        simple: 1 minute ago
      query:
        simple: type:Manual and (status:Pending or status:Active)
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: "Searches Cortex XSOAR Incidents and returnrs the most relevant
        fields. Default search range is the last 30 days, if you want to change this,
        use the fromDate argument. \n\nReturns the id, name, type, severity, status,
        owner, and created/closed times to context.  You can add additional fields
        using the add_field_to_context argument.\n\nThis automation runs using the
        default Limited User role, unless you explicitly change the permissions.  Based
        on the SearchIncidentsV2 from the Common Scripts pack, but more efficient."
      id: 1f8241c1-5301-44b6-8097-f8b5f18589dc
      iscommand: false
      name: searchIncidents triggered >3 in 1 minutes
      script: SearchIncidentsSummary
      type: regular
      version: -1
    taskid: 1f8241c1-5301-44b6-8097-f8b5f18589dc
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 450,
          "y": -20
        }
      }
  "4":
    conditions:
    - condition:
      - - left:
            iscontext: true
            value:
              complex:
                accessor: id
                root: foundIncidents
                transformers:
                - operator: count
          operator: greaterThan
          right:
            value:
              simple: "3"
        - left:
            iscontext: true
            value:
              simple: foundIncidents.name
          operator: greaterThan
          right:
            value:
              simple: "3"
      label: "yes"
    continueonerrortype: ""
    id: "4"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "5"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: e2826ce9-9041-4fc2-8911-91f279d6a8ab
      iscommand: false
      name: Check greater than 3
      type: condition
      version: -1
    taskid: e2826ce9-9041-4fc2-8911-91f279d6a8ab
    timertriggers: []
    type: condition
    view: |-
      {
        "position": {
          "x": 450,
          "y": 150
        }
      }
  "5":
    continueonerrortype: ""
    id: "5"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "6"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 59391399-efd1-4c9a-8888-2da1af4b6127
      iscommand: false
      name: Awiating for analyst Input
      type: regular
      version: -1
    taskid: 59391399-efd1-4c9a-8888-2da1af4b6127
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 240,
          "y": 360
        }
      }
  "6":
    continueonerrortype: ""
    id: "6"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    scriptarguments:
      subject:
        simple: OzanTestAsd
      to:
        simple: OzanTestAsd
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: Sends an email using Gmail.
      id: 709f99e0-240b-46e7-8fb0-62ca96d4d30e
      iscommand: true
      name: se
      script: '|||send-mail'
      type: regular
      version: -1
    taskid: 709f99e0-240b-46e7-8fb0-62ca96d4d30e
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 230,
          "y": 530
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 805,
        "width": 830,
        "x": 230,
        "y": -180
      }
    }
  }
