contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    prevname: ""
    propagationLabels:
    - all
    toServerVersion: ""
id: e330cea0-228d-4aca-8a99-99c089337688
inputs: []
name: Demo - Indicators
outputs: []
quiet: true
starttaskid: "0"
tasks:
  "0":
    continueonerrortype: ""
    id: "0"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "1"
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: fe796328-745b-4eb5-8d88-8846ba7691e2
      iscommand: false
      name: ""
      version: -1
    taskid: fe796328-745b-4eb5-8d88-8846ba7691e2
    timertriggers: []
    type: start
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
  "1":
    continueonerrortype: ""
    id: "1"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    nexttasks:
      '#none#':
      - "2"
    note: false
    quietmode: 0
    scriptarguments:
      add_fields_to_context:
        simple: Supervisor
      query:
        simple: 'type:CSOCAnalyst and value: ${incident.owner}'
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      description: |-
        Searches Cortex XSOAR Indicators.

        Search for XSOAR Indicators and returns the id, indicator_type, value, and score/verdict.

        You can add additional fields from the indicators using the add_field_to_context argument.
      id: 9fa0c084-b0cb-437f-8d75-bc5e48277fc4
      iscommand: false
      name: Test Task 1 Suresh
      script: SearchIndicator
      type: regular
      version: -1
    taskid: 9fa0c084-b0cb-437f-8d75-bc5e48277fc4
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
  "2":
    continueonerrortype: ""
    id: "2"
    ignoreworker: false
    isautoswitchedtoquietmode: false
    isoversize: false
    note: false
    quietmode: 0
    separatecontext: false
    skipunavailable: false
    task:
      brand: ""
      id: 69658f67-2745-4ee8-8070-e9de6ca106a0
      iscommand: false
      name: Test
      type: regular
      version: -1
    taskid: 69658f67-2745-4ee8-8070-e9de6ca106a0
    timertriggers: []
    type: regular
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
version: -1
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 415,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
